name       : doomsday-engine
version    : 2.0.3
release    : 1
source     :
    - http://files.dengine.net/archive/doomsday-2.0.3.tar.gz : eb7b37035637a2ef36cf8128f1380be01838b4576c3b5a962b107a67bedc55fd
license    :
    - GPL-3.0
    - LGPL-3.0
component  : games
summary    : A portable and enhanced source port of the Doom I/II engine.
description: |
    A portable and enhanced source port of the Doom I/II engine.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(assimp)
    - pkgconfig(fluidsynth)
    - pkgconfig(gl)
    - pkgconfig(xrandr)
    - pkgconfig(zziplib)
setup      : |
    cd doomsday/build
    %cmake ..
build      : |
    cd doomsday/build
    %make
install    : |
    cd doomsday/build
    %make_install
