name       : doomsday-engine
version    : 2.1.1
release    : 9
source     :
    - https://sourceforge.net/projects/deng/files/Doomsday%20Engine/2.1.1/doomsday-2.1.1.tar.gz/download : 93bbd0f97a6f32f121d0d846a7f5f2d95dced565a8502ab9f0e9e26fdf30c78a
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : games.action
summary    : A portable and enhanced source port of the Doom I/II engine.
description: |
    A portable and enhanced source port of the Doom I/II engine.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(fluidsynth)
    - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(xrandr)
    - pkgconfig(zziplib)
rundeps    :
    - freepats
    - devel :
        - assimp-devel
setup      : |
    %cmake_ninja -S../doomsday
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Nuke devel files for bundled assimp
    rm -rv $installdir/usr/include/assimp/*
    rmdir $installdir/usr/include/assimp
    rm -v $installdir/%libdir%/doomsday/pkgconfig/assimp.pc
    rmdir $installdir/%libdir%/doomsday/pkgconfig
