name       : doomsday-engine
version    : 2.1.0
release    : 7
source     :
    - https://sourceforge.net/projects/deng/files/Doomsday%20Engine/2.1.0/doomsday-2.1.0.tar.gz/download : 898fb54f59a83311fdaf43118f0c6edefb48f27f276ed65c7a507d82a5667a3e
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : games.action
summary    : A portable and enhanced source port of the Doom I/II engine.
description: |
    A portable and enhanced source port of the Doom I/II engine.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(fluidsynth)
    - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(xrandr)
    - pkgconfig(zziplib)
setup      : |
    %cmake_ninja -S../doomsday
build      : |
    %ninja_build
install    : |
    %ninja_install
