name       : doomsday-engine
version    : 2.1.2
release    : 13
source     :
    - https://sourceforge.net/projects/deng/files/Doomsday%20Engine/2.1.2/doomsday-2.1.2.tar.gz/download : 4362d12b616a035ef21cfd54c3a841900dc6d6614b3d073a50a646ef87ebdc9c
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : games.action
summary    : A portable and enhanced source port of the Doom I/II engine.
description: |
    A portable and enhanced source port of the Doom I/II engine.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(fluidsynth)
    - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(xrandr)
    - pkgconfig(zziplib)
rundeps    :
    - freepats
    - devel :
        - assimp-devel
setup      : |
    %cmake_ninja -S../doomsday
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Nuke devel files for bundled assimp
    rm -rv $installdir/usr/include/assimp/*
    rmdir $installdir/usr/include/assimp
    rm -v $installdir/%libdir%/doomsday/pkgconfig/assimp.pc
    rmdir $installdir/%libdir%/doomsday/pkgconfig
