name       : doomsday-engine
version    : 2.0.3
release    : 2
source     :
    - http://files.dengine.net/archive/doomsday-2.0.3.tar.gz : b1321edf9df4d955601a2cc8d71d2443bd3007a943630f5d473f810678de65d2
license    :
    - GPL-3.0
    - LGPL-3.0
component  : games
summary    : A portable and enhanced source port of the Doom I/II engine.
description: |
    A portable and enhanced source port of the Doom I/II engine.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(assimp)
    - pkgconfig(fluidsynth)
    - pkgconfig(gl)
    - pkgconfig(xrandr)
    - pkgconfig(zziplib)
setup      : |
    cd doomsday/build
    %cmake ..
build      : |
    cd doomsday/build
    %make
install    : |
    cd doomsday/build
    %make_install
